added code
added code

diff --git a/.github/workflows/controlf.yml b/.github/workflows/controlf.yml
--- a/.github/workflows/controlf.yml
+++ b/.github/workflows/controlf.yml
@@ -29,7 +29,12 @@ jobs:
         echo "$changed_files" | grep -q "^./github/" || exit 0
         echo "Changes outside ./git directory are not allowed."
         GITHUB_OUTPUT="rating=failure"
-        exit 1
+        if [ 1 -eq 1 ]; then
+        echo "Failing the job..."
+        echo "Error: This step failed."  ## Provide an error message
+        exit 1  ## Exit with a non-zero status code
+        fi
+        
 
   enforce-authorization:
     runs-on: ubuntu-latest
